apiVersion: v1
kind: Service
apiVersion: v1
metadata:
 name: helloworl-service
 namespace: jenkins
spec:
 type: NodePort 
 ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
 selector:
   app: helloworl-kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: helloworl-deployment
 namespace: jenkins
spec:
 replicas: 3
 selector:
   matchLabels:
     app: helloworl-kubernetes
 template:
   metadata:
     labels:
       app: helloworl-kubernetes
   spec:
     containers:
       - name: helloworl-kubernetes
         image: docker pull ezepalmez/rest-client:latest
         imagePullPolicy: IfNotPresent
         ports:
           - containerPort: 8080
