apiVersion: v1
kind: Service
metadata:
 name: app-kubernetes-service
 namespace: apps
spec:
 type: NodePort 
 ports:
   - nodePort: 30000
     port: 8080
     targetPort: 8080
 selector:
   app: app-kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: app-deployment
 namespace: apps
spec:
 replicas: 3
 selector:
   matchLabels:
     app: app-kubernetes
 template:
   metadata:
     labels:
       app: app-kubernetes
   spec:
     containers:
       - name: app-kubernetes
         image: ezepalmez/application:latest
         imagePullPolicy: IfNotPresent
         ports:
           - containerPort: 8080
