apiVersion: v1
kind: Service
apiVersion: v1
metadata:
 name: app-kubernetes-service
 namespace: apps
spec:
 type: NodePort 
 ports:
  - port: 80
    targetPort: 8080
    nodePort: 30036
    protocol: TCP
 selector:
   app: app-kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: app-deployment
 namespace: apps
spec:
 replicas: 3
 selector:
   matchLabels:
     app: app-kubernetes
 template:
   metadata:
     labels:
       app: app-kubernetes
   spec:
     containers:
       - name: app-kubernetes
         image: ezepalmez/application:latest
         imagePullPolicy: IfNotPresent
         ports:
           - containerPort: 8080
